version: '3.7'

services:
   puller:
     image: yfirmy/eternity2-puller-clue1:2.1.0
     environment:
       - ETERNITY2_SERVER_URL=https://lab.firmy.fr
       - ETERNITY2_SERVER_CLUE1_PASSWORD_FILE=/run/secrets/server_clue1_password
       - ETERNITY2_SOLVER_MACHINE_TYPE="docker-local-machine"
       - ETERNITY2_SOLVER_CLUSTER_NAME="no-cluster"
       - ETERNITY2_SOLVER_JOB_CAPACITY=34
     secrets:
       - server_clue1_password

secrets:
   server_clue1_password:
     file: ../secrets/clue1_password
