apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eternity2-puller-challenge-191
  name: eternity2-puller-challenge-191
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eternity2-puller-challenge-191
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eternity2-puller-challenge-191
    spec:
      containers:
      - image: yfirmy/eternity2-puller-challenge:2.0.0
        name: eternity2-puller-challenge
        imagePullPolicy: Always
        env:
        - name: ETERNITY2_SERVER_URL
          value: "https://lab.firmy.fr"
        - name: ETERNITY2_SERVER_PUZZLE_PASSWORD_FILE
          value: "/app/eternity2-solver/secrets/eternity2_server_password"
        - name: ETERNITY2_SOLVER_MACHINE_TYPE
          value: "minikube-iMac"
        - name: ETERNITY2_SOLVER_CLUSTER_NAME
          value: "minikube"
        - name: ETERNITY2_SOLVER_JOB_CAPACITY
          value: "191"
        volumeMounts:
        - name: password
          mountPath: "/app/eternity2-solver/secrets"
          readOnly: true
        resources: {}
      volumes:
      - name: password
        secret:
          secretName: eternity2-server-challenge-password
status: {}