apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eternity2-c5.24x-191
  name: eternity2-c5.24x-191
spec:
  replicas: 20
  selector:
    matchLabels:
      app: eternity2-c5.24x-191
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eternity2-c5.24x-191
    spec:
      containers:
      - image: yfirmy/eternity2-puller-challenge:2.1.0
        name: eternity2-puller-challenge
        imagePullPolicy: Always
        env:
        - name: ETERNITY2_SERVER_URL
          value: "https://lab.firmy.fr"
        - name: ETERNITY2_SERVER_PUZZLE_PASSWORD_FILE
          value: "/app/eternity2-solver/secrets/eternity2_server_password"
        - name: ETERNITY2_SOLVER_MACHINE_TYPE
          value: "c5.24xlarge"
        - name: ETERNITY2_SOLVER_CLUSTER_NAME
          value: "eternity2-aws-c5-24xlarge"
        - name: ETERNITY2_SOLVER_JOB_CAPACITY
          value: 191
        volumeMounts:
        - name: password
          mountPath: "/app/eternity2-solver/secrets"
          readOnly: true
        resources: {}
      volumes:
      - name: password
        secret:
          secretName: eternity2-server-challenge-password
      nodeSelector:
        instance-type: "c5.24xlarge"
status: {}